language: php

sudo: required
dist: trusty

php:
  - 7.2
  - 7.3

git:
  depth: 1

cache:
  apt: true
  ccache: true
  timeout: 691200
  directories:
    - .temp
    - $HOME/.ccache
    - $HOME/.composer/cache

before_install:
  - export PHP_MAJOR="$(echo $TRAVIS_PHP_VERSION | cut -d '.' -f 1,2)"
  - export PHP_MINOR="$(`phpenv which php` -r 'echo phpversion();' | cut -d '.' -f 2)"
  - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;
  - composer self-update
  - travis_retry composer install --prefer-dist --no-interaction --ignore-platform-reqs

install:
  - echo "extension=bcmath.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

script:
  - vendor/bin/phpcs --extensions=php
  - vendor/bin/codecept run --coverage-xml

after_success:
  - travis_retry php vendor/bin/php-coveralls